In [8]:
# from station_dataframe_generator import StationDataframeGenerator
# from station_dataframe_processor import StationDataframeProcessor
import numpy as np
import pandas as pd

stations = pd.read_json("../../../data/pollution/station_meta_data.json")

ModuleNotFoundError: No module named 'weatherdata'

In [2]:
for station in stations["station_id"].values:
    if station > 515:
        dataframe = StationDataframeGenerator.generate_station_dataframe(station, range(2019, 2023))
        if dataframe is not None:
            dataframe = StationDataframeProcessor().process_station_dataframe(dataframe)
            dataframe.reset_index(inplace=True)
            dataframe.to_feather("../../../data/pollution/processed/interpolated/" + str(station) + ".feather")

In [6]:
df = pd.read_feather("../../../data/pollution/processed/interpolated/pm10/16.feather")

In [7]:
df

,timestamp,temperature_2m,relativehumidity_2m,winddirection_10m,windspeed_10m,precipitation,pm10
0,2019-01-01 01:00:00,1.9,91.0,223.0,7.4,0.0,245.92900
1,2019-01-01 02:00:00,2.2,90.0,223.0,9.4,0.0,75.40170
2,2019-01-01 03:00:00,2.8,89.0,226.0,10.9,0.0,56.37850
3,2019-01-01 04:00:00,3.4,90.0,227.0,11.7,0.0,29.83040
4,2019-01-01 05:00:00,3.9,91.0,228.0,13.0,0.0,1.02620
...,...,...,...,...,...,...,...
34690,2022-12-30 20:00:00,4.6,90.0,193.0,16.2,0.0,20.80240
34691,2022-12-30 21:00:00,4.4,88.0,193.0,17.0,0.0,19.75810
34692,2022-12-30 22:00:00,4.7,84.0,201.0,20.1,0.0,10.71430
34693,2022-12-30 23:00:00,5.1,81.0,202.0,23.7,0.0,11.00650
34694,2022-12-31 00:00:00,5.2,81.0,210.0,23.2,0.0,9.06587